<script setup lang="ts">import{computed}from'vue';import{useRenameStore}from'../../stores/rename';const s=useRenameStore();const depth=computed({get:()=>s.maxDepth??0,set:v=>{s.maxDepth=v===0?null:v;s.invalidateScan()}})</script>
<template><aside class="workflow"><div class="workflow-head"><span>重命名流程</span><small>完成预览后才会允许执行</small></div><ol>
<li><label>1　选择目录</label><div class="row"><el-input :model-value="s.root" readonly placeholder="请选择需要整理的根目录"/><el-button @click="s.chooseRoot">选择</el-button></div></li>
<li><label>2　查找内容 / 查找规则</label><div class="row"><el-input :model-value="s.search" placeholder="例如：旧版" @update:model-value="s.setSearch"/><el-button type="primary" :disabled="!s.canScan" @click="s.scan">扫描</el-button></div><el-checkbox v-model="s.useRegex" @change="s.invalidateScan">使用正则表达式</el-checkbox></li>
<li><label>3　扫描范围</label><div class="checks"><el-checkbox v-model="s.includeDirs" @change="s.invalidateScan">文件夹</el-checkbox><el-checkbox v-model="s.includeFiles" @change="s.invalidateScan">文件</el-checkbox></div><div class="row"><span class="hint">层级（0 为全部）</span><el-input-number v-model="depth" :min="0" :max="99"/></div></li>
<li><label>4　替换为</label><el-input :model-value="s.replacement" placeholder="可留空以删除匹配片段" @update:model-value="s.setReplacement"/><el-checkbox v-model="s.renameExtension" @change="s.invalidatePreview">允许修改扩展名</el-checkbox></li>
<li><label>5　结果预览</label><el-button class="wide" :disabled="!s.canPreview" @click="s.preview">生成安全预览</el-button></li>
<li><label>6　确认执行</label><el-button class="wide" type="primary" :disabled="!s.canExecute" @click="$emit('execute')">确认并执行 {{s.summary.ready}} 项</el-button></li>
</ol><div class="rail-tools"><el-button text @click="$emit('templates')">⌘ 正则模板</el-button><el-button text @click="$emit('settings')">⚙ 设置</el-button></div></aside></template>
<style scoped>.workflow{height:100%;background:var(--surface);border-right:1px solid var(--border);padding:18px;overflow:auto}.workflow-head{display:grid;gap:3px;margin-bottom:14px;font-weight:700}.workflow-head small,.hint{color:var(--muted);font-size:12px;font-weight:400}ol{list-style:none;margin:0;padding:0;display:grid;gap:8px}li{display:grid;gap:9px;padding:13px;border-radius:var(--radius);background:var(--surface-soft)}label{font-size:13px;font-weight:700}.row{display:flex;align-items:center;gap:8px}.checks{display:flex;gap:16px}.wide{width:100%}.rail-tools{display:flex;justify-content:space-between;padding-top:14px}</style>
