import { Channel, invoke } from '@tauri-apps/api/core'
import { open } from '@tauri-apps/plugin-dialog'
import type { MatchOptions, OperationLogV1, RenameCandidate } from '../types/contracts'
export interface PreviewSummary { matched:number; ready:number; unchanged:number; conflicts:number; invalid:number }
export interface ScanProgress { jobId:string; phase:string; scannedTotal:number; matchedTotal:number; warning?:string }
export interface PreviewPage { items:RenameCandidate[]; total:number; offset:number; limit:number; summary:PreviewSummary; warnings:string[] }
export interface OperationSummary { identifier:string; createdAt:string; updatedAt:string; root:string; search:string; replacement:string; status:string; itemCount:number; successCount:number; failedCount:number }
export interface OperationPage { items:OperationSummary[]; total:number }
export interface UndoCheck { operationId:string; token:string; safe:boolean; summary:string; items:Array<{itemIndex:number;currentSource:string;restoreTarget:string;kind:string;safe:boolean;detail:string}> }
export interface DesktopApi { chooseDirectory():Promise<string|null>; startScan(options:MatchOptions,onProgress:(event:ScanProgress)=>void):Promise<string>; cancelActiveJob():Promise<void>; buildPreview(jobId:string,replacement:string,renameExtension:boolean):Promise<PreviewPage>; getPreviewPage(jobId:string,offset:number,limit:number):Promise<PreviewPage>; execute(jobId:string,options:object,onProgress:(event:object)=>void):Promise<{operationId:string;succeeded:number;skipped:number;failed:number}>; queryOperations(query:object):Promise<OperationPage>; getOperation(identifier:string):Promise<OperationLogV1>; checkUndo(identifier:string):Promise<UndoCheck>; undo(identifier:string,token:string,onProgress:(event:object)=>void):Promise<{succeeded:number;failed:number}>; loadPreferences():Promise<{appearance:string}>; savePreferences(appearance:string):Promise<void> }
function events<T>(handler:(event:T)=>void){const channel=new Channel<T>();channel.onmessage=handler;return channel}
export const desktopApi:DesktopApi={async chooseDirectory(){const value=await open({directory:true,multiple:false});return typeof value==='string'?value:null},startScan:(options,h)=>invoke('start_scan',{options,events:events(h)}),cancelActiveJob:()=>invoke('cancel_active_job'),buildPreview:(jobId,replacement,renameExtension)=>invoke('build_rename_preview',{jobId,replacement,renameExtension}),getPreviewPage:(jobId,offset,limit)=>invoke('get_preview_page',{jobId,offset,limit}),execute:(jobId,options,h)=>invoke('execute_rename',{jobId,options,events:events(h)}),queryOperations:(query)=>invoke('query_operations',{query}),getOperation:(identifier)=>invoke('get_operation',{identifier}),checkUndo:(identifier)=>invoke('check_undo',{identifier}),undo:(identifier,token,h)=>invoke('undo_operation',{identifier,token,events:events(h)}),loadPreferences:()=>invoke('load_preferences'),savePreferences:(appearance)=>invoke('save_preferences',{appearance})}
